### ISSUE TITLE
select one or more ISFS stations to plot

### ISSUE THREAD

**Issue by erikj** [ncareol/ncharts#1]
from @maclean 

> One thing we need now is to be able to select one or more ISFS stations to plot.

> The Vertex project has 15 stations, which all have almost the same suite of variables, and then some non-station variables.

**Comment by maclean** [comment]
Stations can now be selected, and it is working for VERTEX (15 stations).
Right now we don't plan to have a station dimension in the ISFS Perdiago dataset.  That will have its own challenges. I'll create an issue for Perdiago.
