### ISSUE TITLE
Remove project DEEPWAVE? Or: why is /scr/isf_apg unreadable?

### ISSUE THREAD

**Issue by erikj** [ncareol/ncharts#16]
The [**DEEPWAVE** project](http://datavis.eol.ucar.edu/ncharts/projects/DEEPWAVE) doesn't currently go anywhere:

- [ISS](http://datavis.eol.ucar.edu/ncharts/platforms/ISS/DEEPWAVE) => [30min_winds](http://datavis.eol.ucar.edu/ncharts/projects/DEEPWAVE/30min_winds) => error because `/scr/isf_apg` is not readable
- [GV](http://datavis.eol.ucar.edu/ncharts/platforms/GV/DEEPWAVE) => _No datasets for platform GV, project DEEPWAVE._

Should the project be removed, or does anyone know why `/scr/isf_apg` is unreadable?

**Comment by garyjg** [comment]
The original /scr/isf_apg disk was decommissioned, so I just submitted JIRA-14811.  I don't know about DEEPWAVE aircraft data.

**Comment by erikj** [comment]
@garyjg great, thanks!

**Comment by erikj** [comment]
mount point updated to `/scr/rain-isf/apg` in `autofs` by Santiago, works now:

http://datavis.eol.ucar.edu/ncharts/projects/DEEPWAVE/30min_winds
