### ISSUE TITLE
dimnames error

### ISSUE THREAD

**Issue by erikj** [ncareol/ncharts#18]
error when plotting weather-station data

> ```
  File "/app/ncharts/views.py", line 862, in post
    vdimnames = dsetvars[vname]["dimnames"]
KeyError: 'dimnames'
```

http://datavis.eol.ucar.edu/ncharts/projects/Weather/flab-5min

**Comment by maclean** [comment]
Just committed changes to  the develop branch to fix this.  Gave it a test on datavis-dev with the weather flab-5min dataset, DEEPWAVE 30min_winds, PECAN soundings and VERTEX.  Seems good now. Will merge to master and install on datavis.

**Comment by erikj** [comment]
thanks!
